[project]
name = 'Savings'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.enhanced-savings-pool]
path = 'contracts/enhanced-savings-pool.clar'
clarity_version = 2
epoch = 2.5

[contracts.savings-pool]
path = 'contracts/savings-pool.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
